services:
    frontend:
        build: ./my-app
        ports: 
            - 3000:3000
        env_file:
            - .env
        volumes:
            - ./my-app:/app
        restart: always
    
    backend:
        build: ./backend
        ports:
            - $BACKEND_PORT:8000
        restart: always
        env_file:
            - .env
        volumes:
            - ./backend/api:/app/api

    adminer:
        image: adminer
        restart: always
        ports:
            - $ADMINER_PORT:8080